//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Library_Management_App.DATABASE
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Book
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_Book()
        {
            this.Checkouts = new HashSet<tb_Checkout>();
        }
    
        public int book_ID { get; set; }
        public string title { get; set; }
        public string author { get; set; }
        public string publisher { get; set; }
        public Nullable<int> ISBN { get; set; }
        public System.DateTime releaseDate { get; set; }
        public string genre { get; set; }
        public string condition { get; set; }
        public string availability { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_Checkout> Checkouts { get; set; }
    }
}
