//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Library_Management_App.DATABASE
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Checkout
    {
        public int checkout_ID { get; set; }
        public int book_ID { get; set; }
        public int patron_ID { get; set; }
        public System.DateTime checkout_Date { get; set; }
        public System.DateTime due_Date { get; set; }
    
        public virtual tb_Book Book { get; set; }
        public virtual tb_Patron Patron { get; set; }
    }
}
