//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Library_Management_App.DATABASE
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_UserInfo
    {
        public int user_ID { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public string email { get; set; }
        public int user_level { get; set; }
    }
}
